version: '3.8'

services:
  playable-preview:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/app/uploads
      - ./public:/app/public
    environment:
      - PORT=3000
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123}
      - BASE_URL=${BASE_URL:-http://localhost:3000}
    restart: unless-stopped